title: IEEE at UC Merced
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: ieeemerced-jekyll-theme
show_excerpts: true

paginate: 3

plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
